version: "3.9"
services:
  emulatorjs-netplay-server:
    image: ghcr.io/emulatorjs/emulatorjs-netplay/emulatorjs-netplay-server:latest
    ports:
      - 3000:3000
    environment:
      - NETPLAY_PASSWORD=admin123
      - NETPLAY_PORT=3000
      - NETPLAY_DEV=false