name: Release Workflow

on:
  push:
    paths:
      - 'package.json'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.version_changed.outputs.version_changed }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: git fetch --all --tags

      - name: Get current version
        id: version
        run: |
          version=$(node -p "require('./package.json').version")
          echo version=${version} >> $GITHUB_OUTPUT

      - name: Get Previous tag
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.1
          prefix: v

      - name: Compare versions
        id: version_changed
        run: |
          version=$(node -p "require('./package.json').version")
          current_version=v${version}
          previous_version="${{ steps.previous_tag.outputs.tag }}"
          
          if [[ "${current_version}" != "${previous_version}" ]]; then
            echo "Version has changed!"
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "Version has not changed."
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Purge artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0

  build-windows:
    needs: [check-version]
    runs-on: windows-latest
    if: ${{ needs.check-version.outputs.changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm ci

      - name: Build Windows
        run: npm run build-win

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          path: |
            dist/*.exe
            dist/*.zip

  build-linux:
    needs: [check-version]
    runs-on: ubuntu-latest
    if: ${{ needs.check-version.outputs.changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm ci

      - name: Build Linux
        run: npm run build-linux

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          path: |
            dist/*.AppImage
            dist/*.zip
            dist/emulatorjs-netplay-server

  build-docker:
    needs: [check-version]
    runs-on: ubuntu-latest
    if: ${{ needs.check-version.outputs.changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Docker image
        run: npm run build-docker

      - name: Publish Docker image to GitHub Packages
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag emulatorjs-netplay-server ghcr.io/emulatorjs/emulatorjs-netplay/emulatorjs-netplay-server:${{ needs.check-version.outputs.version }}
          docker push ghcr.io/emulatorjs/emulatorjs-netplay/emulatorjs-netplay-server:${{ needs.check-version.outputs.version }}
          docker tag emulatorjs-netplay-server ghcr.io/emulatorjs/emulatorjs-netplay/emulatorjs-netplay-server:latest
          docker push ghcr.io/emulatorjs/emulatorjs-netplay/emulatorjs-netplay-server:latest

      - name: Upload Docker artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: docker-compose.yml

  create-release:
    needs: [build-windows, build-linux, build-docker, check-version]
    if: ${{ needs.check-version.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      
      - name: Download windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: windows-artifacts
          path: dist/

      - name: Download linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: linux-artifacts
          path: dist/

      - name: Download docker artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: dist/

      - name: Rename Files
        run: |
          mv "dist/emulatorjs-netplay-server" "dist/EmulatorJS Netplay Server-linux-${{ needs.check-version.outputs.version }}"
          mv "dist/emulatorjs-netplay-server-${{ needs.check-version.outputs.version }}.zip" "dist/EmulatorJS Netplay Server-linux-${{ needs.check-version.outputs.version }}.zip"
          mv "dist/EmulatorJS Netplay Server-${{ needs.check-version.outputs.version }}.AppImage" "dist/EmulatorJS Netplay Server App-linux-${{ needs.check-version.outputs.version }}.AppImage"
          mv "dist/EmulatorJS Netplay Server ${{ needs.check-version.outputs.version }}.exe" "dist/EmulatorJS Netplay Server App-windows-${{ needs.check-version.outputs.version }}.exe"
          mv "dist/EmulatorJS Netplay Server-${{ needs.check-version.outputs.version }}-win.zip" "dist/EmulatorJS Netplay Server-windows-${{ needs.check-version.outputs.version }}.zip"
          mv "dist/emulatorjs-netplay-server.exe" "dist/EmulatorJS Netplay Server-windows-${{ needs.check-version.outputs.version }}.exe"
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check-version.outputs.version }}
          release_name: v${{ needs.check-version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Docker
        id: upload-release-asset-docker
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/docker-compose.yml
          asset_name: docker-compose.yml
          asset_content_type: application/yml
      
      - name: Upload Release Asset Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/EmulatorJS Netplay Server-linux-${{ needs.check-version.outputs.version }}
          asset_name: EmulatorJS Netplay Server-linux-${{ needs.check-version.outputs.version }}
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Linux Zip
        id: upload-release-asset-linux-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/EmulatorJS Netplay Server-linux-${{ needs.check-version.outputs.version }}.zip
          asset_name: EmulatorJS Netplay Server-linux-${{ needs.check-version.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset Linux AppImage
        id: upload-release-asset-linux-appimage
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/EmulatorJS Netplay Server App-linux-${{ needs.check-version.outputs.version }}.AppImage
          asset_name: EmulatorJS Netplay Server App-linux-${{ needs.check-version.outputs.version }}.AppImage
          asset_content_type: application/appimage

      - name: Upload Release Asset Windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/EmulatorJS Netplay Server-windows-${{ needs.check-version.outputs.version }}.exe
          asset_name: EmulatorJS Netplay Server-windows-${{ needs.check-version.outputs.version }}.exe
          asset_content_type: application/exe

      - name: Upload Release Asset Windows Zip
        id: upload-release-asset-windows-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/EmulatorJS Netplay Server-windows-${{ needs.check-version.outputs.version }}.zip
          asset_name: EmulatorJS Netplay Server-windows-${{ needs.check-version.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset Windows App
        id: upload-release-asset-windows-app
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/EmulatorJS Netplay Server App-windows-${{ needs.check-version.outputs.version }}.exe
          asset_name: EmulatorJS Netplay Server App-windows-${{ needs.check-version.outputs.version }}.exe
          asset_content_type: application/exe

      - name: Purge artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0